### ISSUE TITLE
Website for Shopping App

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback4-example-shopping#425]
In the Shopping App Brainstorming session last week, it was decided that we will upgrade [loopback4-example-shopping ](https://github.com/strongloop/loopback4-example-shopping) to have a corresponding website.

**Acceptance Criteria**

- [x] [Authentication and authorization clean up](https://github.com/strongloop/loopback4-example-shopping/issues/432)
- [x] [CRUD operations on shopping carts](https://github.com/strongloop/loopback4-example-shopping/issues/475)
- [ ] [CRUD operations on orders](https://github.com/strongloop/loopback4-example-shopping/issues/474)
- [x] [View products](https://github.com/strongloop/loopback4-example-shopping/issues/439)
- [ ] [CRUD operation on products](https://github.com/strongloop/loopback4-example-shopping/issues/440)
- [x] [Order products](https://github.com/strongloop/loopback4-example-shopping/issues/441)
- [ ] [Product recommendation](https://github.com/strongloop/loopback4-example-shopping/issues/442)
- [ ] [Persona](https://github.com/strongloop/loopback4-example-shopping/issues/443)
- [ ] [UI testing](https://github.com/strongloop/loopback4-example-shopping/issues/476)
- [ ] [Documentation](https://github.com/strongloop/loopback4-example-shopping/issues/477)
- [ ] [Misc.](https://github.com/strongloop/loopback4-example-shopping/issues/478)

**Comment by dhmlau** [comment]
Let's move it to the `loopback4-example-shopping` because we'll be implementing the frontend in here.
